package model;

public enum MetroEventsEnum {
    OPEN_METROSTATION,
    BUY_METROCARD,
    BUY_METROCARD_TICKETS,
    ACTIVATE_METROGATE,
    INVALID_SCAN,
    ILLEGAL_WALKTHROUGH,
    WALKTHROUGH_GATE,
    CLOSE_METROSTATION,
    SCAN_METROGATE;
}